CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    pwd TEXT NOT NULL
);

CREATE TABLE programs (
    id INT GENERATED by DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    active BOOLEAN DEFAULT FALSE,
    day INT DEFAULT 1,
    rotation_pos INT DEFAULT 1,
    rotations INT DEFAULT 999999999,
    deload_interval INT NULL,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE workouts (
    id INT GENERATED by DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

--figure out how we should handle sets and history
CREATE TABLE exercises (
    id INT GENERATED by DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rep_range_lower INT NOT NULL,
    rep_range_upper INT NOT NULL,
    sets INT NOT NULL,
    rest_seconds INT DEFAULT 0,
    note TEXT NULL,
    workout_id INT NOT NULL REFERENCES workouts(id) ON DELETE CASCADE
);

CREATE TABLE program_days (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id INT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
    day_order INT NOT NULL,
    workout_id INT NULL REFERENCES workouts(id) ON DELETE SET NULL,
    UNIQUE (program_id, day_order)
);
